num_show_pigs = 5000
num_pigs_per_fence = 10000
min_mean_to_median = 4.0
max_mean_to_median = 8.0
pmb_rtp = 1.0
simulation_trials = 5000
test_spins = [10, 20, 50]
test_spins_weights = [0.6, 0.2, 0.2]
score_type = "rtp"
max_trial_dist = 15

game_name = "candy_carnage_1000"
bet_type = "regular_buy"  # change this per run: base | bonus_hunt | regular_buy | super_buy
path_to_games = "../games/"
run_1000_batch = false
threads_for_fence_construction = 20
threads_for_show_construction = 20
